core:
  - all:
      - changed-files:
          - any-glob-to-any-file: "lua/tokyomoonight/**"
          - all-globs-to-all-files:
              - "!lua/tokyomoonight/groups/**"
              - "!lua/tokyomoonight/colors/**"
              - "!lua/tokyomoonight/extra/**"

extras:
  - changed-files:
      - any-glob-to-any-file: "lua/tokyomoonight/extra/**"

groups:
  - changed-files:
      - any-glob-to-any-file: "lua/tokyomoonight/groups/**"

base:
  - changed-files:
      - any-glob-to-any-file:
          - "lua/tokyomoonight/groups/base.lua"
          - "lua/tokyomoonight/groups/kinds.lua"
          - "lua/tokyomoonight/groups/treesitter.lua"
          - "lua/tokyomoonight/groups/semantic_tokens.lua"

colors:
  - changed-files:
      - any-glob-to-any-file: "lua/tokyomoonight/colors/**"
